---
- hosts: all
  tasks:
  - name: Install toolchain
    community.general.pacman:
      name: 
      - git
      - make
      - unzip
      - mingw-w64-x86_64-cmake
      - mingw-w64-x86_64-lld
      - mingw-w64-x86_64-clang
      - mingw-w64-x86_64-cairo
      - mingw-w64-x86_64-freetype
      - mingw-w64-x86_64-gnutls
      - mingw-w64-x86_64-libxslt
      - mingw-w64-x86_64-icu
      - mingw-w64-x86_64-openjpeg2

  - name: Create ~/pkg directory
    ansible.builtin.file:
      path: ~/pkg/
      state: directory
      mode: '0755'

  - name: Create ~/git directory
    ansible.builtin.file:
      path: ~/git/
      state: directory
      mode: '0755'

  - name: Clone libobjc2
    git: 
      repo: "https://github.com/gnustep/libobjc2"
      dest: ~/git/libobjc2
      version: "master"

  - name: Create ~/git/libobjc2/build directory
    ansible.builtin.file:
      path: ~/git/libobjc2/build
      state: directory
      mode: '0755'

  - name: Clone tools-make
    git: 
      repo: "https://github.com/gnustep/tools-make"
      dest: ~/git/tools-make
      version: "make-2_9_1"

  - name: Clone libs-base
    git: 
      repo: "https://github.com/qmfrederik/libs-base"
      dest: ~/git/libs-base
      version: "ucrt64"

  - name: Clone libs-gui
    git: 
      repo: "https://github.com/qmfrederik/libs-gui"
      dest: ~/git/libs-gui
      version: "ucrt64"

  - name: Clone libs-back repository
    git:
      repo: https://github.com/qmfrederik/libs-back
      dest: ~/git/libs-back
      version: "ucrt64"

  - name: Clone plugins-themes-WinUXTheme repository
    git:
      repo: https://github.com/qmfrederik/plugins-themes-WinUXTheme
      dest: ~/git/plugins-themes-WinUXTheme
      version: "ucrt64"

  - name: Create ~/dist directory
    ansible.builtin.file:
      path: ~/dist/
      state: directory
      mode: '0755'
